jenkinsci/templating-engine-plugin

src/main/groovy/org/boozallen/plugins/jte/config/TemplateConfigDsl.groovy
src/test/groovy/org/boozallen/plugins/jte/config/TemplateConfigDslSpec.groovy

having a configuration file with a field such as
~~~
field = [ "a", "b-c" ]
~~~
resulted in the exception: 
~~~
java.lang.SecurityException: 
onMethodCall:
invoker -> org.kohsuke.groovy.sandbox.impl.Checker$1@ab631b1
receiver -> PROPERTY_MISSING
method -> minus
args -> [PROPERTY_MISSING]
~~~
being thrown. 
Ended up being because ``TemplateConfigDsl.serialize`` did not appropriately handle arrays. 
updated TemplateConfigDsl.serialize to properly handle arrays via the ``inspect()`` method.
wrote a unit test for this case.

Arrays in config files

---

docs/index.rst
docs/pages/Job_Configurations/github_org.rst
docs/pages/Job_Configurations/pipeline.rst
docs/pages/Job_Configurations/repository.rst
docs/pages/Job_Configurations/template_step.rst
src/main/groovy/org/boozallen/plugins/jte/config/GovernanceTier.groovy
src/main/groovy/org/boozallen/plugins/jte/job/MultibranchTemplateFlowDefinition.groovy
src/main/groovy/org/boozallen/plugins/jte/job/TemplateBranchProjectFactory.groovy
src/main/resources/org/boozallen/plugins/jte/job/TemplateFlowDefinition/config.jelly
src/main/resources/org/boozallen/plugins/jte/job/TemplateFlowDefinition/help-pipelineConfig.html
src/main/resources/org/boozallen/plugins/jte/job/TemplateFlowDefinition/help-sandbox.html
src/main/resources/org/boozallen/plugins/jte/job/TemplateFlowDefinition/help-template.html
src/test/groovy/org/boozallen/plugins/jte/config/GovernanceTierSpec.groovy

When using a regular Pipeline Job, the ``template`` step allows you to pass a closure that will be executed after initializing the binding based upon what's in the aggregated pipeline configuration. 
These Pipeline jobs do not necessarily require that an SCM be used, meaning that there was no way to add a job level ``pipeline_config.groovy`` file. 
This change adds a new FlowDefinition to Pipeline Jobs that allows you to specify your pipeline template and pipeline configuration file directly in the Jenkins UI. 
1. Renamed the existing Flow Definition to ``MultibranchFlowDefinition`` as it is only used in the context of Multibranch and GitHub Organization jobs. 
2. Created a new ``TemplateFlowDefinition`` for the purposes described above
3. Updated ``GovernanceTier.getHierarchy()`` to …

Pipeline Job Flow Definition to pass template and config file directly

---

docs/pages/Primitives/application_environments.rst
src/main/groovy/org/boozallen/plugins/jte/binding/injectors/ApplicationEnvironmentInjector.groovy
src/main/resources/org/boozallen/plugins/jte/binding/injectors/ApplicationEnvironment.groovy
src/test/groovy/org/boozallen/plugins/jte/binding/injectors/ApplicationEnvironmentSpec.groovy

Application Environment primitives can now determine the previous and next Application Environment via ``.next`` and ``.previous`` 
add next and previous properties to ApplicationEnvironment and update the injector to populate these properties during initialization 
Unit Test coverage

ApplicationEnvironments can determine previous/next environment

---

src/main/resources/org/boozallen/plugins/jte/binding/injectors/Stage.groovy
src/main/resources/org/boozallen/plugins/jte/binding/injectors/StepWrapper.groovy
src/test/groovy/org/boozallen/plugins/jte/binding/injectors/StageSpec.groovy

Stages will now pass any arguments to the stages defined within, for example a deployment stage that can contain multiple steps can be re-used with an application environment so that steps can be dynamic based on the environment passed in
See: https://github.com/linead/jte-testing/tree/master/stages-with-envs for a simple example of a stage with behaviour based on stages
- Initial testing via unit tests
- Manual testing via a dockerised jenkins instance running jenkins 2.164.3 with the following repos
- https://github.com/linead/jte-testing/tree/master/stages-with-envs
- https://github.com/linead/jte-jobs
Not sure about labels to add to the PR, but can update the documentation to reflect this if the code changes look fine

allow stages to pass parameters down to their steps

---

src/main/groovy/org/boozallen/plugins/jte/binding/TemplatePrimitiveInjector.groovy
src/main/resources/org/boozallen/plugins/jte/hooks/Hooks.groovy

We came across #26 when we upgraded to 1.3 after facing a more intermittent issue in 1.1.1 with serialization. 
I tried a few different things to expose this via testing but I couldn't work out exactly how to make jenkins serialize the method at the right point. 
The hooks class is now marked as NonCPS when it discovers the hooks to avoid line 39 trying to serialize a method object which fails due to it being not serializable.
We've run a patched version of 1.3 with NonCPS and it resolved the issue. Our pipeline includes a class utilising hooks as well as stages and libraries.

Fix hook serialization error

---

build.gradle
src/main/groovy/org/boozallen/plugins/jte/utils/TemplateScriptEngine.groovy

The exception message thrown by LinkageError when the same class is parsed twice changed between JDK 8 and JDK 11.  This implements as much cleaner way of handling this case. 
Stop interpreting the LinkageError exception message and actually check the class loader's class cache. 
All unit tests pass and manually tested against jenkins/jenkins:lts and jenkins/jenkins:lts-jdk11

JDK 11 Support - fixes issue #28

---

build.gradle
src/main/groovy/org/boozallen/plugins/jte/config/TemplateConfigDsl.groovy
src/test/groovy/org/boozallen/plugins/jte/config/TemplateConfigDslSpec.groovy

String block names in the ``pipeline_config.groovy`` file that included hyphens were incorrectly serialized resulting in a sandbox exception being thrown. 
For example, 
~~~
"some-block"{ }
~~~
resulted in 
~~~
Scripts not permitted to use method groovy.lang.GroovyObject invokeMethod java.lang.String java.lang.Object (org.boozallen.plugins.jte.config.TemplateConfigBuilder$BuilderMethod minus org.boozallen.plugins.jte.config.TemplateConfigBuilder$BuilderMethod). Administrators can decide whether to approve or reject this signature.
[Pipeline] End of Pipeline
org.jenkinsci.plugins.scriptsecurity.sandbox.RejectedAccessException: Scripts not permitted to use method groovy.lang.GroovyObject invokeMethod java.lang.String java.lang.Object …

Fix hyphenated blocks in config

---

build.gradle

Otherwise `gradle build` fails as follows:
> No value has been specified for property 'mainClassName'.

Remove unused 'application' Gradle plugin

---

src/main/groovy/org/boozallen/plugins/jte/config/TemplateConfigDsl.groovy
src/test/groovy/org/boozallen/plugins/jte/config/TemplateConfigDslSpec.groovy

Fix to accept forward slashes in config blocks.
This is a minor update to code that already exists in the `TemplateConfigDslSpec`. Besides just accepting hyphens, this change will also allow the config to accept directory slashes.
I added and ran unit tests to the `TemplateConfigDslSpec.groovy` file which are passing.

Fix forward slashes in config.

---

.gitignore
docs/modules/pipeline-templating/pages/configuration_files.adoc
src/main/groovy/org/boozallen/plugins/jte/TemplateEntryPointVariable.groovy
src/main/groovy/org/boozallen/plugins/jte/config/TemplateConfigDsl.groovy
src/main/groovy/org/boozallen/plugins/jte/config/TemplateConfigDslSandbox.groovy
src/main/groovy/org/boozallen/plugins/jte/utils/RunUtils.groovy
src/test/groovy/org/boozallen/plugins/jte/config/GovernanceTierSpec.groovy
src/test/groovy/org/boozallen/plugins/jte/config/PipelineConfigSpec.groovy
src/test/groovy/org/boozallen/plugins/jte/config/TemplateConfigDslSpec.groovy
src/test/groovy/org/boozallen/plugins/jte/config/TemplateEntryPointVariableSpec.groovy
src/test/groovy/org/boozallen/plugins/jte/config/libraries/ScmLibraryProviderSpec.groovy

resolves #49 
Updated the ``TemplateConfigDsl.parse`` method to include the ``EnvActionImpl`` made available to pipeline's via the ``env`` variable. 
This means that any Jenkins environment variables that have been defined, or Build Parameters, will now be resolvable in pipeline configuration files. 
Unit tests && integration testing

allow pipeline configuration files to reference 'env' variable

---

src/main/groovy/org/boozallen/plugins/jte/job/TemplateBranchProjectFactory.groovy

Fixed missing import
Fixed the missing ScmPipelineConfigurationProvider import in the TemplateBranchProjectFactory class
- Created a docker container:
```
docker run -d -v jenkins_home:/var/jenkins_home -p 8080:8080 -p 50000:50000 jenkins/jenkins:2.226-jdk11
```
- Built the JPI:
```
make jpi
```
- Copied the hpi file to /var/jenkins_home/plugins using `docker cp`
- Tested that the "Exclude branches without a pipeline configuration file" was working by scanning the multibranch.
- Ran unit tests

Added missing import

---

docs/modules/library-development/pages/lifecycle_hooks.adoc
src/main/groovy/org/boozallen/plugins/jte/hooks/HookContext.groovy
src/main/resources/org/boozallen/plugins/jte/TemplateEntryPoint.groovy
src/main/resources/org/boozallen/plugins/jte/binding/injectors/StepWrapper.groovy
src/main/resources/org/boozallen/plugins/jte/hooks/AnnotatedMethod.groovy
src/main/resources/org/boozallen/plugins/jte/hooks/Hooks.groovy
src/test/groovy/org/boozallen/plugins/jte/binding/injectors/StepWrapperSpec.groovy

In order to fix #74, the `currentBuild.result` is no longer automatically set to `SUCCESS` at the beginning of a JTE pipeline run. 
In resolving this, the `context` parameter passed to Lifecycle Hooks no longer requires the build status to be set.  This result has been removed from context parameters due to the fact that the `currentBuild` variable can be accessed to fetch the same information. 
This `currentBuild` variable, not specific to JTE, has also been made resolvable within Lifecycle Hook's optional Closure parameter that determines whether or not the hook should be executed. 
* Stop setting `currentBuild.result = SUCCESS` in TemplateEntryPoint 
* Remove `context.status` from the Lifecycle Hook's context parameter
* Convert the context parameter to a dedicated `HookContext` class …

Do not set currentBuild.result to success at the beginning of the build

---

src/main/groovy/org/boozallen/plugins/jte/job/TemplateMultiBranchProjectFactory.groovy

Fix using JTE in an organization project
Using the plugin with an organization project results in the following error
```
Could not load actions from org.boozallen.plugins.jte.job.TemplateMultiBranchProjectFactory$PerFolderAdder@36a861db for jenkins.branch.OrganizationFolder@646734cb[my-organization]
groovy.lang.MissingPropertyException: No such property: Item for class: org.boozallen.plugins.jte.job.TemplateMultiBranchProjectFactory
```
I have not tested this. I don't have much experience with testing or even building jenkins plugins but guidance is welcome.

Fix missing import in TemplateMultiBranchProjectFactory.groovy

---

src/main/groovy/org/boozallen/plugins/jte/init/GroovyShellDecoratorImpl.groovy
src/main/groovy/org/boozallen/plugins/jte/init/governance/libs/PluginLibraryProvider.groovy
src/main/groovy/org/boozallen/plugins/jte/init/governance/libs/ScmLibraryProvider.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/StepWrapperFactory.groovy
src/main/resources/org/boozallen/plugins/jte/init/primitives/hooks/AnnotatedMethod.groovy
src/main/resources/org/boozallen/plugins/jte/init/primitives/hooks/Hooks.groovy
src/main/resources/org/boozallen/plugins/jte/init/primitives/injectors/StepWrapper.groovy
src/test/groovy/org/boozallen/plugins/jte/init/governance/libs/ScmLibraryProviderSpec.groovy

JTE pipelines can survive an ungraceful restart now, which was the impetus for much of the refactoring we’re doing for JTE v2.0.
The source code of a library step gets compiled into a Script object and stored on a StepWrapper.
Previously, we just stored the Script object itself.  for some reason, when jenkins restarts that Script object fails to be executed.  some sort of classloader issue.
so the fix was:
1. vendor the source of the library steps into each build’s directory in JENKINS_HOME
2. set the Script field on StepWrapper to transient so we don’t bother persisting it
3. instead - store a pointer to where the source code for the library step lives
4. memoize the getter for the Script object so that if it’s no longer present (in the event of an ungraceful restart) - we can reparse it …

restart working

---

build.gradle
config/codenarc/rules.groovy
docs/modules/library-development/pages/lifecycle_hooks.adoc
docs/modules/primitives/pages/stages.adoc
src/main/groovy/org/boozallen/plugins/jte/init/GroovyShellDecoratorImpl.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/ReservedVariableName.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/TemplatePrimitiveInjector.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/hooks/HookInjector.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/ApplicationEnvironmentInjector.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/KeywordInjector.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/LibraryLoader.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/PipelineConfigVariableInjector.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/StageInjector.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/StepWrapperFactory.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/StepWrapperScript.java
src/main/java/org/boozallen/plugins/jte/init/primitives/injectors/StepWrapperScript.java
src/main/resources/org/boozallen/plugins/jte/init/primitives/hooks/AnnotatedMethod.groovy
src/main/resources/org/boozallen/plugins/jte/init/primitives/hooks/Hooks.groovy
src/main/resources/org/boozallen/plugins/jte/init/primitives/injectors/Stage.groovy
src/main/resources/org/boozallen/plugins/jte/init/primitives/injectors/StepWrapper.groovy
src/test/groovy/org/boozallen/plugins/jte/init/primitives/hooks/HookSpec.groovy
src/test/groovy/org/boozallen/plugins/jte/init/primitives/injectors/StepWrapperSpec.groovy

* changes the approach to autowiring variables and functionality to library steps.
* a `StageContext` class has been created to formalize that data structure as opposed to passing a `Map` around
* autowires the `hookContext` to steps and removes the step method parameter
Previously, JTE handles autowiring of values and some functionality via runtime metaprogramming. 
This PR introduces a new `GroovyShellDecorator` that customizes the compilation for library steps to set a custom runtime base script. 
- unit tests pass
Beyond the auto-wiring of `hookContext` variable, the changes should be transparent to end users.

Implement StepWrapper Base Class, autowire HookContext

---

src/main/groovy/org/boozallen/plugins/jte/init/GroovyShellDecoratorImpl.groovy

This PR sets a > 0 ordinal on JTE's `GroovyShellDecoratorImpl` as part of the effort to support declarative syntax.
According to the `@Extension` [javadocs](https://javadoc.jenkins.io/hudson/Extension.html#ordinal--), extensions with greater ordinal values are listed first. 
This ensures that the JTE compile-time changes take place prior to the compile-time parsing that declarative syntax does. 
For more info, check out the [corresponding pull request on pipeline-model-definition](https://github.com/jenkinsci/pipeline-model-definition-plugin/pull/403)
marking this as a draft.  will wait to see if there are changes on either side (JTE/Declarative) that we want to include to this. 
**Will need to write a page in the documentation that should be included in this PR prior to merging.**

Support Declarative Syntax

---

Version_2.adoc
docs/modules/pipeline-templating/pages/configuration_files.adoc
src/main/groovy/org/boozallen/plugins/jte/init/PipelineDecorator.groovy
src/main/groovy/org/boozallen/plugins/jte/init/governance/config/dsl/PipelineConfigurationObject.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/TemplateBindingFactory.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/LibraryStepInjector.groovy
src/test/groovy/org/boozallen/plugins/jte/init/PipelineDecoratorSpec.groovy
src/test/groovy/org/boozallen/plugins/jte/init/primitives/injectors/LibraryStepInjectorSpec.groovy

from #104 implemented library tier reversing by adding a jte{ reverse_library_resolution = Boolean } setting
(default) reverse_library_resolution = false -> library loading uses the current JTE loading
reverse_library_resolution = true -> goes in the reverse order of above
Unit tests

Reverse library tiers

---

build.gradle
src/main/groovy/org/boozallen/plugins/jte/init/PipelineDecorator.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/TemplateBinding.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/StageInjector.groovy
src/main/resources/org/boozallen/plugins/jte/init/primitives/injectors/Stage.groovy
src/test/groovy/org/boozallen/plugins/jte/init/ResumabilitySpec.groovy
src/test/groovy/org/boozallen/plugins/jte/init/primitives/injectors/GlobalCollisionValidatorSpec.groovy
src/test/groovy/org/boozallen/plugins/jte/init/primitives/injectors/JteBlockValidatorSpec.groovy
src/test/groovy/org/boozallen/plugins/jte/init/primitives/injectors/PipelineConfigVariableSpec.groovy
src/test/groovy/org/boozallen/plugins/jte/job/AdHocTemplateFlowDefinitionSpec.groovy
src/test/groovy/org/boozallen/plugins/jte/util/TestUtil.groovy

fixes #158 describing a bug in JTE resumability.  This PR resolves that bug. 
`GroovyShellDecoratorImpl` rehydrates the run's populated `TemplateBinding` by fetching it from the `PipelineDecorator` action.  For some reason, the `TemplateBinding` on the action had been set to transient -- resulting in a `null` binding on restart.
Unit tests

Fixes Resumability Bug - #158

---

src/main/groovy/org/boozallen/plugins/jte/init/governance/config/dsl/PipelineConfigurationDsl.groovy
src/test/groovy/org/boozallen/plugins/jte/init/governance/config/dsl/PipelineConfigurationObjectSpec.groovy

This PR fixes #174 
Was seeing a situation where having more than pipeline configuration was throwing an exception, specifically: 
```
groovy.lang.MissingMethodException: No signature of method: org.boozallen.plugins.jte.init.governance.config.dsl.PipelineConfigurationBuilder$BuilderMethod.or() is applicable for argument types: (org.boozallen.plugins.jte.init.governance.config.dsl.PipelineConfigurationBuilder$BuilderMethod) values: [PROPERTY_MISSING]
```
The root cause of this was improperly serialized pipeline configuration. Specifically, having a regular expression pattern that used regex groups. 
For this specific use case, the offending line was `master = ~/[Mm](aster|ain)/`. 
In JTE, when aggregating two pipeline configurations, we create a copy of the current and incoming pipeline …

Resolve #174

---

src/main/groovy/org/boozallen/plugins/jte/init/governance/libs/PluginLibraryProvider.groovy

fixes #168.
When parsing the jar file and reading it's contents, JTE isn't handling `library_config.goovy` files or directory entries properly.
I rebuilt JTE with the changes and loaded it into my local Jenkins environment and confirmed that it would proceed past that point.

Fix bug in how PluginLibraryProvider reads jar contents - #168

---

src/main/groovy/org/boozallen/plugins/jte/init/governance/libs/PluginLibraryProvider.groovy
src/main/groovy/org/boozallen/plugins/jte/init/governance/libs/ScmLibraryProvider.groovy
src/test/groovy/org/boozallen/plugins/jte/init/governance/libs/ScmLibraryProviderSpec.groovy

Previously, libraries would only be found if a populated `steps` directory was present. 
Now that libraries can contribute classes via the `src` directory, the criteria for finding a library has been updated. 
It is now possible for a library to only contribute classes or only contribute steps or both.

hasLibrary is true if steps or src present

---

build.gradle

Right now, the [JTE JavaDocs on the Plugin Site](https://javadoc.jenkins.io/plugin/templating-engine/) are only showing the contents of `src/main/java`. 
This PR updates the `build.groovy` file to override the default behavior of the `javadocJar` task to "trick" the plugin site into showing the groovydocs (which include the `src/main/java` content as well).
I ran
> ./gradlew javadocJar
and then after switching to the `build/libs` directory, i exploded the javadoc jar file via:
> jar xf *-javadoc.jar
and then validated that `index.html` was the groovydocs vs the javadocs.

Fix JTE javadoc on the plugin site

---

Justfile

Trying to automate common workflows as I notice them. 
Once a feature branch has been merged from a fork to `main`, run
> just finish
which will:
1. make sure you aren't doing something silly
2. sync your forks main with upstream main 
3. delete your feature branch both locally and remotely in your fork

add convenience justfile recipe for cleaning up feature branch

---

src/main/groovy/org/boozallen/plugins/jte/init/primitives/TemplatePrimitiveCollector.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/DefaultStepInjector.groovy
src/main/resources/org/boozallen/plugins/jte/init/primitives/injectors/StageCPS.groovy
src/test/groovy/org/boozallen/plugins/jte/init/ResumabilitySpec.groovy

Utilizes a `@NonCPS` method in `StagesCPS` to fetch `StepWrappers` for the stage's steps to prevent resumability issues when using stages. 
fixes #195 
unit tests reproduced the issue and then confirmed the fix

Stop storing non-serializable TemplatePrimitiveCollector in `StageCPS`

---

build.gradle

We used to have an edge-case where we used dependencies from `github-branch-source` directly.
This no longer appears to be the case.

remove unnecessary dependency on github-branch-source

---

src/main/groovy/org/boozallen/plugins/jte/init/primitives/TemplateBinding.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/TemplatePrimitive.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/TemplatePrimitiveNamespace.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/Keyword.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/Stage.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/StepWrapper.groovy
src/main/resources/org/boozallen/plugins/jte/init/primitives/injectors/StageCPS.groovy
src/test/groovy/org/boozallen/plugins/jte/init/primitives/TemplateBindingSpec.groovy

Each `TemplatePrimitive`'s `getValue()` makes a call to `isOverloaded()` to throw an exception if a user tries to directly access a primitive that has an ambiguous name. This could be the case if `jte.permissive_initialization` is set to `true`. 
Unfortunately, we did not factor this in to the way that `TemplatePrimitiveNamespace`s fetch their primitives when accessed via the long-name notation. 
This PR overloads `getValue(CpsScript script, Boolean skipOverloaded = false)` such that the logic to throw exception on overloaded primitives can be skipped when the primitive is accessed via the namespace. 
Unit test added to confirm the use case.

fix 205 by having TemplatePrimitiveNamespace override check isOverloaded

---

src/main/groovy/org/boozallen/plugins/jte/init/primitives/TemplatePrimitive.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/TemplatePrimitiveNamespace.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/Stage.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/StepWrapper.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/StepWrapperFactory.groovy
src/main/resources/org/boozallen/plugins/jte/init/primitives/injectors/StageCPS.groovy
src/main/resources/org/boozallen/plugins/jte/init/primitives/injectors/StepWrapperCPS.groovy
src/test/groovy/org/boozallen/plugins/jte/init/primitives/TemplateBindingSpec.groovy

Cleaning up a lot of .... suboptimal... code in `StepWrapperFactory`, `StepWrapper`, `StepWrapperCPS`, and `StageCPS`
1. There was no reason for `StepWrapperCPS` to extend `StepWrapper`. Simplified by giving `StepWrapperCPS` a reference to its parent `StepWrapper`
2. Added `AutoClone` transformation to `StepWrapper` rather than implement the `Cloneable` interface by hand. 
3. `StepWrapperCPS` having a `call` method was an artifact from when we stored `TemplatePrimitive`s in the `TemplateBinding`. Not needed anymore.  Therefore, the code reuse via `invoke` was no longer needed so I deleted and moved code into `methodMissing`. 
4. Simplified `StepWrapperFactory`'s `prepareScript` method signature and re-ordered builder methods up to the top of the file to increase class readability
5. After …

Chore: Code Cleanup for `StepWrapper`, `StepWrapperCPS`, and `StepWrapperFactory`

---

src/main/resources/org/boozallen/plugins/jte/util/TemplateLogger/Annotator/script.js

When [timestamper](https://plugins.jenkins.io/timestamper/) plugin is enabled, also show and hide timestamps in job output when pressing _show_ and _hide_ links instead of just getting a series of timestamps in a row when the content is collapsed.
Example of incorrect behaviour:
This Javascript change hooks into the toggle code and when toggling, if a previous sibling HTML element exists with the `timestamp` CSS class, toggles it along with the JTE output.
Also fixes some whitespace in the file.
Change was tested by changing the JS code directly in a running Jenkins instance

Show and hide timestamps in job output

---

docs/reference/library-configuration-schema.md

Update [Library Configuration Schema](https://jenkinsci.github.io/templating-engine-plugin/2.3/reference/library-configuration-schema/) page to address Issue #226 and PR #242 and cleanup some formatting issues.
Added `ArrayList` to list of validation parameter options.
Fixed table footnote formatting.
Minor emphasis/consistency changes.
Running `just lint-docs` and `just serve`

library config docs update

---

.markdownlint-cli2.yaml
docs/Dockerfile
docs/concepts/library-development/library-configuration-file.md
docs/concepts/library-development/library-structure.md
docs/concepts/library-development/parameterizing-libraries.md
docs/concepts/library-development/step-aliasing.md
docs/concepts/pipeline-templates/declarative-syntax.md
docs/contributing/developer/releasing.md
docs/reference/library-configuration-schema.md
docs/styles/Vocab/JTE/accept.txt
mkdocs.yml

Updating [docs theme](https://github.com/squidfunk/mkdocs-material/) to latest.
Updated container image used for docs to latest: [8.0.4](https://hub.docker.com/layers/squidfunk/mkdocs-material/8.0.4/images/sha256-25cd187896afa72c61f7a35e0225cef8a7dca2241070564b86d89d5b734c27c7?context=explore)
Swapped out manual footnotes in code blocks with new [code annotations](https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations)
Locally using `just lint-docs` and `just serve` to review

[Documentation]: docs theme update

---

docs/concepts/pipeline-configuration/overview.md
docs/concepts/pipeline-governance/pipeline-template-selection.md
src/main/groovy/org/boozallen/plugins/jte/init/PipelineConfigurationAggregator.groovy
src/main/groovy/org/boozallen/plugins/jte/init/PipelineTemplateResolver.groovy
src/main/groovy/org/boozallen/plugins/jte/job/MultibranchTemplateFlowDefinition.groovy
src/main/groovy/org/boozallen/plugins/jte/job/TemplateBranchProjectFactory.groovy
src/main/groovy/org/boozallen/plugins/jte/job/TemplateMultiBranchProjectFactory.groovy
src/main/resources/org/boozallen/plugins/jte/job/TemplateBranchProjectFactory/config.jelly
src/main/resources/org/boozallen/plugins/jte/job/TemplateBranchProjectFactory/help-configurationPath.html
src/main/resources/org/boozallen/plugins/jte/job/TemplateBranchProjectFactory/help-filterBranches.html
src/main/resources/org/boozallen/plugins/jte/job/TemplateMultiBranchProjectFactory/config.jelly
src/main/resources/org/boozallen/plugins/jte/job/TemplateMultiBranchProjectFactory/help-configurationPath.html
src/main/resources/org/boozallen/plugins/jte/job/TemplateMultiBranchProjectFactory/help-filterBranches.html
src/main/resources/org/boozallen/plugins/jte/job/TemplateMultiBranchProjectFactory/help-scriptPath.html
src/test/groovy/org/boozallen/plugins/jte/job/TemplateBranchProjectFactorySpec.groovy

Enable configuration of custom paths for template and config files when retrieving them from the source code repository for Multibranch projects to address issue https://github.com/jenkinsci/templating-engine-plugin/issues/99
`TemplateBranchProjectFactory` and `TemplateMultiBranchProjectFactory` have been modified to store a new `String configurationPath` (which defaults to `pipeline_config.groovy`) and allows users to specify which path in the repository to fetch the pipeline configuration file from instead of always fetching from root. Also enabled this same selection for the pipeline template file via field `String scriptPath` which defaults to `Jenkinsfile`.
`MultibranchTemplateFlowDefinition` has been updated to account for these fields, and thus the `PipelineConfigurationAggregator` …

Set custom path for pipeline configuration file in the source code repository

---

src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/GlobalCollisionValidator.groovy
src/test/groovy/org/boozallen/plugins/jte/init/primitives/injectors/GlobalCollisionValidatorSpec.groovy

The `GlobalCollisionValidator` would previously throw an exception when more than 128 steps were loaded.
Explicitly casting to a `List` resolves this error. 
fixes #256 
Behavior reproduced both via a test and manually in a live Jenkins instance.
The test now passes and the fix has been confirmed against a live Jenkins instance.

Resolve exceptions when loading more than 128 files

---

src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/ApplicationEnvironment.groovy
src/test/groovy/org/boozallen/plugins/jte/init/primitives/injectors/ApplicationEnvironmentSpec.groovy

The `ApplicationEnvironment` primitive was previously checking the object prior to checking the user provided definition of the application environment in the pipeline configuration. 
This meant that for certain fields, such as `name`, the value would return unexpected results.
fixes #254 
Updated the order in which properties on the `ApplicationEnvironment` class are fetched. 
We now first check the pipeline configuration definition and then proceed to the object itself. 
If no property is found, we still return `null`. 
Unit tests.

Application Environment ignores user configuration for `name` 

---

src/main/groovy/org/boozallen/plugins/jte/init/primitives/TemplatePrimitiveNamespace.groovy
src/test/groovy/org/boozallen/plugins/jte/init/primitives/TemplatePrimitiveNamespaceSpec.groovy

Ensure arguments are passed correctly to steps when invoked via primitive namespace

---

docs/concepts/library-development/multi-method-steps.md

One of the code blocks in [this page](https://jenkinsci.github.io/templating-engine-plugin/2.4/concepts/library-development/multi-method-steps/) doesn't display appropriately. managed to fix this inappropriate code block display.
just reformatted the `md` file
tested this by previewing the markdown file.
- before:
- after:

fix inappropriate code block display

---

Justfile
src/main/groovy/org/boozallen/plugins/jte/init/PipelineConfigurationAggregator.groovy
src/main/groovy/org/boozallen/plugins/jte/init/PipelineTemplateResolver.groovy
src/main/groovy/org/boozallen/plugins/jte/init/governance/config/ScmPipelineConfigurationProvider.groovy
src/main/groovy/org/boozallen/plugins/jte/init/governance/libs/ScmLibraryProvider.groovy
src/main/groovy/org/boozallen/plugins/jte/job/ScmAdHocTemplateFlowDefinitionConfiguration.groovy
src/main/groovy/org/boozallen/plugins/jte/util/FileSystemWrapper.groovy
src/main/groovy/org/boozallen/plugins/jte/util/FileSystemWrapperFactory.groovy
src/test/groovy/org/boozallen/plugins/jte/init/governance/config/ScmPipelineConfigurationProviderSpec.groovy
src/test/groovy/org/boozallen/plugins/jte/init/governance/libs/ScmLibraryProviderSpec.groovy
src/test/groovy/org/boozallen/plugins/jte/job/AdHocTemplateFlowDefinitionSpec.groovy

A long awaited refactoring of how `FileSystemWrapper` works.
`FileSystemWrapper`, previously, had static constructor methods that would instantiate an instance and then instance methods to populate the object's fields. 
These instance methods had multiple return parameters and overall made the code hard to reason about.
Furthermore, the creation of a `FileSystemWrapper` would swallow exceptions without logging them.
`FileSystemWrapper` has been split into two classes.  A `FileSystemWrapperFactory` now handles the creation of `FileSystemWrapper` objects through a single `create` method. 
Most exception handling has been removed so as to surface unexpected behavior when JTE is unable to fetch files.
Unit Tests have been refactored to pass.
TODO: integration testing on a real Jenkins with …

Refactor FileSystemWrapper

---

src/main/groovy/org/boozallen/plugins/jte/init/PipelineConfigurationAggregator.groovy
src/main/groovy/org/boozallen/plugins/jte/init/PipelineTemplateResolver.groovy
src/main/groovy/org/boozallen/plugins/jte/init/governance/libs/ScmLibraryProvider.groovy
src/main/groovy/org/boozallen/plugins/jte/job/MultibranchTemplateFlowDefinition.groovy
src/main/groovy/org/boozallen/plugins/jte/job/TemplateBranchProjectFactory.groovy
src/main/groovy/org/boozallen/plugins/jte/job/TemplateFlowDefinition.groovy
src/main/groovy/org/boozallen/plugins/jte/job/TemplateMultiBranchProjectFactory.groovy
src/main/groovy/org/boozallen/plugins/jte/util/FileSystemWrapperFactory.groovy
src/test/groovy/org/boozallen/plugins/jte/init/primitives/injectors/GlobalCollisionValidatorSpec.groovy

fixes #264 
PR #252 inadvertently broke backwards compatibility by adding fields without a corresponding entry in `readResolve`.
This PR addresses that bug while simplifying some of the code contributed via the addition of abstract methods on `TemplateFlowDefinition`. 
Each extension of `TemplateFlowDefinition` must now implement `getPipelineConfiguration` and `getTemplate` methods to avoid conditional statements in `PipelineConfigurationAggregator` and `PipelineTemplateResolver` based on the class of the `FlowDefinition`. 
unit tests all continue to pass.

Add backwards compatibility from 2.3 

---

src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/StepWrapper.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/StepWrapperScriptPickle.groovy
src/test/groovy/org/boozallen/plugins/jte/init/ResumabilitySpec.groovy

fixes #191 
Adds a `StepWrapperScriptPickle` to assist in unmarshalling a compiled step during pipeline resumption.
Reproduced error via unit tests
Tests pass. 
Reproduced error in a live Jenkins and validated fix.

Ensure pipeline's can resume when Jenkins restarts mid-step

---

.github/workflows/CI.yml
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/StepWrapperScriptPickle.groovy
src/main/groovy/org/boozallen/plugins/jte/job/TemplateFlowDefinition.groovy
src/test/groovy/org/boozallen/plugins/jte/ReplaySpec.groovy
src/test/groovy/org/boozallen/plugins/jte/ResumabilitySpec.groovy

fixes #222 
fixes #225 
The `TemplatePrimitiveCollector` action that's responsible for giving the pipeline access to `TemplatePrimitive`s was not being added for replays of pipelines.
unit tests reproduced the error and then passed with the fix.

Resolve pipeline replay failures

---

src/main/groovy/org/boozallen/plugins/jte/init/governance/libs/PluginLibraryProvider.groovy

fixes #268 
all credit goes to @connorh23 for finding the fix! 
The `PluginLibraryProvider` was mistaking checking if a library didn't have a `src` directory _**or**_ a `steps` directory instead of checking that **both** don't exist. 
error reproduced and fix validated manually.

Resolve bug in plugin-provided library sources requiring a `src` directory.

---

src/main/groovy/org/boozallen/plugins/jte/init/primitives/TemplatePrimitiveInjector.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/hooks/HookInjector.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/ApplicationEnvironmentInjector.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/DefaultStepInjector.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/GlobalCollisionValidator.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/KeywordInjector.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/LibraryStepInjector.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/PipelineConfigVariableInjector.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/StageInjector.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/TemplateMethodInjector.groovy

Previously - each `TemplatePrimitiveInjector` was responsible for fetching the run's `TemplatePrimitiveCollector`, adding a `TemplatePrimitiveNamespace` to it, and then saving it back to the run in the right way. 
To simplify this... this PR changes the interface so that `TemplatePrimitiveInjector.injectPrimitives(...)` is expected to just return a `TemplatePrimitiveNamespace`.
Similarly, the `TemplatePrimitiveNamespace.validatePrimitives(...)` interface now receives the `TemplatePrimitiveCollector` as an argument so it doesn't have to fetch the collector itself. 
unit tests pass after refactor

Simplify the `TemplatePrimitiveInjector` interfaces

---

src/main/groovy/org/boozallen/plugins/jte/init/primitives/TemplatePrimitiveInjector.groovy
src/test/groovy/org/boozallen/plugins/jte/init/primitives/injectors/StepWrapperSpec.groovy

fixes #291 
a bug was introduced by #283 that caused a regression in template methods working as expected. 
PR #283 introduced a bug where the `TemplatePrimitiveCollector` was not being persisted after each `TemplatePrimitiveInjector`. 
This resulted in `TemplateMethodInjector` not being able to access the `TemplatePrimitives` that had been created by `LibraryStepInjector`. 
The fix was to update the `TemplatePrimitiveInjector.invoke$` method so that the updated `TemplatePrimitiveCollector` is persisted on the `WorkflowRun` after each injector is invoked. 
reproduced the bug both manually and in unit tests.
confirmed that the change fixes both.

Resolved a regression of `template_methods` working when overloaded by library steps

---

src/main/groovy/org/boozallen/plugins/jte/init/primitives/TemplatePrimitiveInjector.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/ApplicationEnvironmentInjector.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/LibraryStepInjector.groovy
src/main/groovy/org/boozallen/plugins/jte/util/AggregateException.groovy
src/main/groovy/org/boozallen/plugins/jte/util/ConfigValidator.groovy
src/test/groovy/org/boozallen/plugins/jte/init/primitives/injectors/ApplicationEnvironmentSpec.groovy
src/test/groovy/org/boozallen/plugins/jte/util/ConfigValidatorSpec.groovy

fixes #253 
also improves how `AggregateExceptions` are printed to the build log
Previously `AggregateException` would print the individual exception messages but there was no way to see the stack traces for those individual exceptions. 
<details><summary> previous screen shots </summary>
</details>
When expanding the above image, you'd again just see the same message and single stack trace
<details><summary> expanded </summary>
</details>
This has been updated so that each exception message is individually printed and when expanded shows the stack track for that exception.
<details><summary> New Console Log Screenshot </summary>
</details>
unit tests

Add Configuration Validation to Application Environment parsing

---

src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/KeywordInjector.groovy

Might solve #311, just based on the stack trace. Or might not, or might cause other problems, or fix this one only to have the next JEP-200 violation break. Totally untested, YMMV.

Do not save a `GString` as `Keyword.value`

---

.github/workflows/CI.yml
build.gradle

following up #321 to the [latest recommendation](https://www.jenkins.io/doc/developer/plugin-development/choosing-jenkins-baseline/#currently-recommended-versions) for the jenkins baseline to support. 
This will now require a version of Jenkins that requires Java 11. 
Also upgrading spotless to the latest version

upgrade jenkins baseline to recommended version 2.387.3

---

src/main/groovy/org/boozallen/plugins/jte/init/primitives/TemplateBinding.groovy
src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/StepWrapperFactory.groovy
src/test/groovy/org/boozallen/plugins/jte/ReplaySpec.groovy
src/test/groovy/org/boozallen/plugins/jte/ResumabilitySpec.groovy

This change fixes #318.
When replaying a JTE pipeline job, the `TemplateBinding` attached to the pipeline template and library steps had a stale instance of the `DSL` object stored as `steps`.  This change updates the `TemplateBinding` to create a new `DSL` object on each access to the `steps` variable.

Fixes #318: create new DSL object on each access of steps var in TemplateBinding

---

docs/concepts/library-development/library-source.md

fixes #303 
The documentation links to the required content, but absolute links in mkdocs don't work because of the version number introduced into the URLs by `mike`.

Fix broken link in docs

---

src/main/groovy/org/boozallen/plugins/jte/util/SandboxWhitelist.groovy
src/test/groovy/org/boozallen/plugins/jte/init/primitives/injectors/LibraryStepInjectorSpec.groovy

fixes #343
adds step related classes to the pipeline whitelist now that library steps are sandboxed when loaded from a folder library source.
added unit tests that reproduce regression

fix #343 by adding step related classes to whitelist
